Update patch set 1
Patch Set 1:

Error after docker-compose build command:

E: There were unauthenticated packages and -y was used without --allow-unauthenticated

ERROR: Service 'knotctl' failed to build: The command '/bin/sh -c apt-get update  && apt-get install -y       nodejs yarn dbus' returned a non-zero code: 100

Patch-set: 1